// File for Test the API in VScode using "humao.rest-client" extension

### Create User
POST http://localhost:8080/user HTTP/1.1
Content-Type: application/json

{
    "name": "John Doe",
    "age": 30
}

### Get User
GET http://localhost:8080/user/1 HTTP/1.1

### Delete User
DELETE http://localhost:8080/user/1 HTTP/1.1